# docker-compose build && docker-compose up -d
# If "docker-compose logs ckan" shows DB not ready, run "docker-compose restart ckan" a few times.
version: "3"

volumes:
  collectivat_ckan_config:
  collectivat_ckan_storage:
  collectivat_pg_data:
  collectivat_solr_data:

services:
  ckan:
    container_name: collectivat_ckan
    build:
      dockerfile: Dockerfile_production
      context: ../../
      args:
          - CKAN_SITE_URL=${CKAN_SITE_URL}
    command: /usr/lib/ckan/venv/bin/gunicorn --paste /etc/ckan/production.ini
    restart: always
    links:
      - db
      - solr
      - redis
    expose:
      - "5000"
    # ports:
    #   - "0.0.0.0:${CKAN_PORT}:5000"
    environment:
      # Defaults work with linked containers, change to use own Postgres, SolR, Redis or Datapusher
      - CKAN_SQLALCHEMY_URL=postgresql://ckan:${POSTGRES_PASSWORD}@collectivat_db/ckan
      - CKAN_DATASTORE_WRITE_URL=postgresql://ckan:${POSTGRES_PASSWORD}@collectivat_db/datastore
      - CKAN_DATASTORE_READ_URL=postgresql://datastore_ro:${DATASTORE_READONLY_PASSWORD}@collectivat_db/datastore
      - CKAN_SOLR_URL=http://collectivat_solr:8983/solr/ckan
      - CKAN_REDIS_URL=redis://collectivat_redis:6379/1
      - CKAN_DATAPUSHER_URL=http://collectivat_datapusher:8800
      - CKAN_SITE_URL=${CKAN_SITE_URL}
      - CKAN_MAX_UPLOAD_SIZE_MB=${CKAN_MAX_UPLOAD_SIZE_MB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}

    volumes:
      # - ./production.ini:/etc/ckan/production.ini
      - collectivat_ckan_config:/etc/ckan
      - collectivat_ckan_storage:/var/lib/ckan
    networks:
      - collectivat_ckan_default

  datapusher:
    container_name: collectivat_datapusher
    image: datapusher:latest
    command: /usr/lib/ckan/datapusher/bin/gunicorn -b 0.0.0.0:8800 --workers 3 --capture-output deployment.datapusher_wsgi:application
    restart: always
    expose:
      - "8800"
    environment:
      - CKAN_PUBLIC_DOMAIN=${CKAN_PUBLIC_DOMAIN}
      - CKAN_INTERNAL_DOMAIN=collectivat_ckan:5000
      - JOB_CONFIG=/usr/lib/ckan/datapusher/src/deployment/datapusher_settings.py
      - PYTHONUNBUFFERED=TRUE
    networks:
      - collectivat_ckan_default

  db:
    container_name: collectivat_db
    build:
      context: ../../
      dockerfile: contrib/docker/postgresql/Dockerfile
      args:
        - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    environment:
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - collectivat_pg_data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - collectivat_ckan_default
    # ports: 
    #   - 5434:5432 

  solr:
    container_name: collectivat_solr
    build:
      context: ../../
      dockerfile: contrib/docker/solr/Dockerfile
    restart: always
    volumes:
      - collectivat_solr_data:/opt/solr/server/solr/ckan
    networks:
      - collectivat_ckan_default

  redis:
    container_name: collectivat_redis
    image: redis:latest
    restart: always
    networks:
      - collectivat_ckan_default

  # nginx:
  #   container_name: nginx_ckan
  #   build: ./nginx
  #   ports:
  #     - 80:80
  #   links:
  #     - ckan
  #   networks:
  #     - collectivat_ckan_default

networks:
  collectivat_ckan_default:
